# Funding for PrismReview.
# Uncomment and populate the line(s) below once sponsorship is open.
# github: [feather100]
# patreon: # Replace with a Patreon username
# open_collective: # Replace with an Open Collective username
# liberapay: # Replace with a Liberapay username
# issuehunt: # Replace with an IssueHunt username
# custom: # Replace with up to 4 custom sponsorship URLs
